version: 4.0.0-aci-{build}
image: Visual Studio 2017 RC
environment:
  CLI_VERSION: 1.0.0-rc4-004842

build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build -c Release --version-suffix "aci-${env:APPVEYOR_BUILD_NUMBER}"
  - ps: dotnet test -c Release tests\Freya.Routers.Uri.Template.Hopac.Tests\Freya.Routers.Uri.Template.Hopac.Tests.fsproj
  - ps: dotnet test -c Release tests\Freya.Routers.Uri.Template.Tests\Freya.Routers.Uri.Template.Tests.fsproj
  - ps: dotnet benchmarks\Freya.Routers.Uri.Template.Benchmarks\bin\Release\netcoreapp1.1\Freya.Routers.Uri.Template.Benchmarks.dll
  - ps: dotnet pack -c Release --include-symbols --version-suffix "aci-${env:APPVEYOR_BUILD_NUMBER}"

test: off

artifacts:
  - path: '**\*.nupkg'
  - path: '**\BenchmarkDotNet.Artifacts\**\*.*'
